services:
  golang-dev:
    container_name: golang-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    volumes:
      - ../:/workspace:cached
    working_dir: /workspace
    networks:
      - default
    command: sleep infinity

  db-chat-branch:
    container_name: db-chat-branch
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: chat_branch
    volumes:
      - chat-branch-data:/var/lib/mysql
      - ../db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - default

volumes:
  chat-branch-data:

networks:
  default:
    driver: bridge
